### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by zlovin** [Nexela/CircuitAlerter#3]
Added CircuitAlerter to an existing game, this occurred on load:
Error while running the on_init: **CircuitAlerter**/actors/circuit-alerter-actor.lua: 1422: attempt to call field 'init_player' (a nil value).

**Comment by Nexela** [comment]
[Fixed](https://github.com/Nexela/CircuitAlerter/commit/cee4f9b945ac7500fa43185c167b3443fe69eac6) 2 bugs with this one. The nil value and hopefully the reason why that part was even getting called.
