### ISSUE TITLE
0.14.8: on_robot_built_entity crash

### ISSUE THREAD

**Issue by gmt** [Nexela/CircuitAlerter#5]
Decided to blow up my base but forgot I was wearing robots.  I suspect I blew up a lamp from your mod and my personal bots replaced it.  Regardless, I got this:

 111.149 Error MainLoop.cpp:749: Exception at tick 16779255: Error while running event on_robot_built_entity (ID 14)
LuaEntity doesn't contain key built_by.
stack traceback:
        **CircuitAlerter**/actors/circuit-alerter-actor.lua:81: in function 'createEntity'
        **CircuitAlerter**/lib/actor_system.lua:59: in function 'createEntity'
        **CircuitAlerter**/control.lua:149: in function <**CircuitAlerter**/control.lua:146>

**Comment by Nexela** [comment]
change from factorio  .14.7, I should have a fix up tonight.

The simplest fix is just a find and replace built_by to last_user (I think last_user) either way, update will be tonight.

**Comment by Nexela** [comment]
Latest update fixes

**Comment by gmt** [comment]
lovely thanks!
