### ISSUE TITLE
0.15?

### ISSUE THREAD

**Issue by abordoli** [Nexela/CircuitAlerter#6]
Any plans to port this up to 0.15?
Regards,
~B

**Comment by Nexela** [comment]
Currently on the back burner for now. It may be revived at some point, in the mean time there are a few other alerter type mods on the portal

**Comment by abordoli** [comment]
I liked yours because it seemed to alert you right at your character's position.

**Comment by Nexela** [comment]
I will see what I can do

**Comment by abordoli** [comment]
Let me know if I can be of assistance...
